extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
env:
  browser: true
globals:
  graphql: true
rules:
  space-before-function-paren: 0
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  react/forbid-prop-types: 0
  jsx-a11y/label-has-for: [2, "required": { "some": [ "nesting", "id" ] }]
settings:
  import/core-modules: [ webpack-dashboard/plugin, react, prop-types, react-helmet ]
